SCHEMA_VERSION = "1.0"
SUBJECT_PREFIX = "aicery.events.v1."

SUBJECT_RUN_STARTED = f"{SUBJECT_PREFIX}run.started"
SUBJECT_RUN_COMPLETED = f"{SUBJECT_PREFIX}run.completed"
SUBJECT_RUN_FAILED = f"{SUBJECT_PREFIX}run.failed"
SUBJECT_AGENT_STEP = f"{SUBJECT_PREFIX}agent.step"
SUBJECT_TOOL_CALLED = f"{SUBJECT_PREFIX}tool.called"
