from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    database_url: str = "postgresql+psycopg://aicery:aicery@localhost:5433/aicery"
    api_version: str = "0.0.1"
    api_key: str = "dev"
    nats_url: str = "nats://localhost:4223"
    nats_enabled: bool = True
    gemini_api_key: str | None = None
    gemini_model: str = "gemini-2.5-flash"  # GEMINI_MODEL env override
    openai_api_key: str | None = None
    openai_model: str = "gpt-4o-mini"
    groq_api_key: str | None = None
    groq_model: str = "llama-3.3-70b-versatile"
    anthropic_api_key: str | None = None
    anthropic_model: str = "claude-3-5-haiku-20241022"
    workspace_root: str = "."
    use_mock_provider: bool = False
    allowed_http_hosts: str = "api.github.com,httpbin.org"
    chaos_tool_fail_rate: float = 0.0
    redis_url: str = "redis://localhost:6380/0"
    rate_limit_enabled: bool = True
    rate_limit_per_minute: int = 100
    rate_limit_backend: str = "redis"  # redis | memory
    rate_limit_at_gateway_only: bool = False
    provider_failover_enabled: bool = True
    qdrant_url: str = "http://localhost:6333"
    qdrant_collection: str = "workspace_chunks"
    semantic_search_enabled: bool = True
    embedding_model: str = "gemini-embedding-001"
    embedding_dimensions: int = 768
    default_workspace_id: str = "local"
    index_embed_batch_size: int = 32
    index_async_path_threshold: int = 10
    blob_storage_enabled: bool = False
    minio_endpoint: str = "localhost:9000"
    minio_access_key: str = "minioadmin"
    minio_secret_key: str = "minioadmin"
    minio_bucket: str = "aicery-workspaces"
    minio_secure: bool = False
    usage_export_enabled: bool = True
    usage_webhook_url: str | None = None
    usage_webhook_secret: str | None = None
    hot_memory_enabled: bool = False
    hot_memory_backend: str = "memory"  # memory | redis
    hot_memory_turn_limit: int = 20
    hot_memory_ttl_sec: int = 86400
    max_graph_steps: int = 20
    trust_gateway_headers: bool = False
    jwt_enabled: bool = False
    jwt_secret: str = "change-me-in-production"
    jwt_algorithm: str = "HS256"
    jwt_audience: str | None = None
    jwt_expire_minutes: int = 60
    otel_enabled: bool = False
    otel_exporter_otlp_endpoint: str | None = None
    otel_service_name: str = "aicery-runtime"
    otel_exporter_otlp_protocol: str = "http/protobuf"
    otel_resource_attributes: str | None = None
    hitl_enabled: bool = True
    hitl_approval_ttl_sec: int = 300
    hitl_timeout_action: str = "reject"  # reject | approve (reject recommended)
    hitl_sweeper_enabled: bool = True
    hitl_sweeper_interval_sec: int = 30
    langgraph_checkpoint_enabled: bool = True
    langgraph_checkpoint_backend: str = "postgres"  # postgres | memory
    router_llm_enabled: bool = False
    router_llm_provider: str = "mock"
    router_llm_model: str = "mock"
    router_llm_confidence_threshold: float = 0.6
    router_rule_short_circuit: float = 0.85
    router_llm_timeout_sec: float = 5.0
    plugin_paths: str = ""
    privacy_proxy_enabled: bool = False
    privacy_proxy_fail_closed: bool = True
    context_compactor_enabled: bool = False
    compactor_turn_threshold: int = 15
    compactor_char_threshold: int = 8000
    execute_code_enabled: bool = False
    sandbox_runner_url: str = "http://localhost:8091"
